name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: dependencies
      run: |
        sudo apt-get install mingw-w64
        go env -w GOPRIVATE=github.com/phil-fly/generate
        git config --global url."https://${{ secrets.ACCESS_TOKEN }}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
        GOOS=windows GOARCH=amd64 go get -u "github.com/phil-fly/generate"

    - name: Build
      run: GOOS=windows GOARCH=amd64 CC=x86_64-w64-mingw32-gcc CGO_ENABLED=1 go build -ldflags ldflags="-s -w -H=windowsgui -w -X generate.RemoteAddr=10.10.27.11 -X generate.RemotePort=8080 -X main.GenerateMod=auto -X main.Rid=GfM4Luk"
